# Feature Encoding

* OneHotEncoding
* Label Encoding

In [40]:
#import libraries
import pandas as pd 
import numpy as np 
import seaborn as sns

#import scikit
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, \
                               StandardScaler, RobustScaler,MinMaxScaler

In [52]:
#import the data

data = sns.load_dataset("tips")
data.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [55]:
#select cat coll

cat_coln = data.select_dtypes("category")
cat_coln

        sex smoker   day    time
0    Female     No   Sun  Dinner
1      Male     No   Sun  Dinner
2      Male     No   Sun  Dinner
3      Male     No   Sun  Dinner
4    Female     No   Sun  Dinner
..      ...    ...   ...     ...
239    Male     No   Sat  Dinner
240  Female    Yes   Sat  Dinner
241    Male    Yes   Sat  Dinner
242    Male     No   Sat  Dinner
243  Female     No  Thur  Dinner

[244 rows x 4 columns]

In [58]:
#encode gender using ONE

#instantiate ohe
ohe = OneHotEncoder(sparse_output=False, dtype="int", drop="first")

gender_en = ohe.fit_transform(data[["sex"]])

gedner_en1 = pd.DataFrame(gender_en, columns=["sex_male"])
gedner_en1

     sex_male
0           0
1           1
2           1
3           1
4           0
..        ...
239         1
240         0
241         1
242         1
243         0

[244 rows x 1 columns]

In [59]:
merged_df = pd.concat([data,gedner_en1],axis=1)
merged_df

     total_bill   tip     sex smoker   day    time  size  sex_male
0         16.99  1.01  Female     No   Sun  Dinner     2         0
1         10.34  1.66    Male     No   Sun  Dinner     3         1
2         21.01  3.50    Male     No   Sun  Dinner     3         1
3         23.68  3.31    Male     No   Sun  Dinner     2         1
4         24.59  3.61  Female     No   Sun  Dinner     4         0
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         1
240       27.18  2.00  Female    Yes   Sat  Dinner     2         0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         1
242       17.82  1.75    Male     No   Sat  Dinner     2         1
243       18.78  3.00  Female     No  Thur  Dinner     2         0

[244 rows x 8 columns]

In [60]:
#drop gender column
del merged_df["sex"]

merged_df

     total_bill   tip smoker   day    time  size  sex_male
0         16.99  1.01     No   Sun  Dinner     2         0
1         10.34  1.66     No   Sun  Dinner     3         1
2         21.01  3.50     No   Sun  Dinner     3         1
3         23.68  3.31     No   Sun  Dinner     2         1
4         24.59  3.61     No   Sun  Dinner     4         0
..          ...   ...    ...   ...     ...   ...       ...
239       29.03  5.92     No   Sat  Dinner     3         1
240       27.18  2.00    Yes   Sat  Dinner     2         0
241       22.67  2.00    Yes   Sat  Dinner     2         1
242       17.82  1.75     No   Sat  Dinner     2         1
243       18.78  3.00     No  Thur  Dinner     2         0

[244 rows x 7 columns]

In [68]:
#option 2, using get dummies
day_dummy = pd.get_dummies(data["day"], dtype="int", drop_first=True)
day_dummy

     Fri  Sat  Sun
0      0    0    1
1      0    0    1
2      0    0    1
3      0    0    1
4      0    0    1
..   ...  ...  ...
239    0    1    0
240    0    1    0
241    0    1    0
242    0    1    0
243    0    0    0

[244 rows x 3 columns]

In [86]:
#one encoding multiple columns
data1 = sns.load_dataset("tips")
data1.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [87]:
#select cat colns
cat_colns = data1.select_dtypes("category")

cat_colns

        sex smoker   day    time
0    Female     No   Sun  Dinner
1      Male     No   Sun  Dinner
2      Male     No   Sun  Dinner
3      Male     No   Sun  Dinner
4    Female     No   Sun  Dinner
..      ...    ...   ...     ...
239    Male     No   Sat  Dinner
240  Female    Yes   Sat  Dinner
241    Male    Yes   Sat  Dinner
242    Male     No   Sat  Dinner
243  Female     No  Thur  Dinner

[244 rows x 4 columns]

In [88]:
#OHE

cat_ohe = pd.get_dummies(cat_colns,dtype="int", drop_first=True)
cat_ohe

     sex_Female  smoker_No  day_Fri  day_Sat  day_Sun  time_Dinner
0             1          1        0        0        1            1
1             0          1        0        0        1            1
2             0          1        0        0        1            1
3             0          1        0        0        1            1
4             1          1        0        0        1            1
..          ...        ...      ...      ...      ...          ...
239           0          1        0        1        0            1
240           1          0        0        1        0            1
241           0          0        0        1        0            1
242           0          1        0        1        0            1
243           1          1        0        0        0            1

[244 rows x 6 columns]

In [89]:
#merged the data

merged_df1 = pd.concat([data1, cat_ohe], axis=1)

merged_df1

     total_bill   tip     sex smoker   day    time  size  sex_Female  smoker_No  day_Fri  day_Sat  day_Sun  time_Dinner
0         16.99  1.01  Female     No   Sun  Dinner     2           1          1        0        0        1            1
1         10.34  1.66    Male     No   Sun  Dinner     3           0          1        0        0        1            1
2         21.01  3.50    Male     No   Sun  Dinner     3           0          1        0        0        1            1
3         23.68  3.31    Male     No   Sun  Dinner     2           0          1        0        0        1            1
4         24.59  3.61  Female     No   Sun  Dinner     4           1          1        0        0        1            1
..          ...   ...     ...    ...   ...     ...   ...         ...        ...      ...      ...      ...          ...
239       29.03  5.92    Male     No   Sat  Dinner     3           0          1        0        1        0            1
240       27.18  2.00  Female    Yes   Sat  Dinner     2           1          0        0        1        0            1
241       22.67  2.00    Male    Yes   Sat  Dinner     2           0          0        0        1        0            1
242       17.82  1.75    Male     No   Sat  Dinner     2           0          1        0        1        0            1
243       18.78  3.00  Female     No  Thur  Dinner     2           1          1        0        0        0            1

[244 rows x 13 columns]

In [90]:
#drop the cat colns

merged_df1.drop(cat_colns, axis=1, inplace=True)
merged_df1

     total_bill   tip  size  sex_Female  smoker_No  day_Fri  day_Sat  day_Sun  time_Dinner
0         16.99  1.01     2           1          1        0        0        1            1
1         10.34  1.66     3           0          1        0        0        1            1
2         21.01  3.50     3           0          1        0        0        1            1
3         23.68  3.31     2           0          1        0        0        1            1
4         24.59  3.61     4           1          1        0        0        1            1
..          ...   ...   ...         ...        ...      ...      ...      ...          ...
239       29.03  5.92     3           0          1        0        1        0            1
240       27.18  2.00     2           1          0        0        1        0            1
241       22.67  2.00     2           0          0        0        1        0            1
242       17.82  1.75     2           0          1        0        1        0            1
243       18.78  3.00     2           1          1        0        0        0            1

[244 rows x 9 columns]

## Label Encoder

In [91]:
#one encoding multiple columns
data3 = sns.load_dataset("tips")
data3.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [95]:
#labelencode day variable

#instantiate labelencoder
le = LabelEncoder()
day_le = le.fit_transform(data3[["day"]])

day_le

C:\Users\DELL\Anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

In [96]:
#one encoding multiple columns
data1 = sns.load_dataset("tips")
data1.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [104]:
import statsmodels.formula.api as smf

In [107]:
lr =smf.ols('tip~size + C(sex) + C(smoker)+ C(day) + C(time)', data=data1).fit()

lr.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    tip   R-squared:                       0.252
Model:                            OLS   Adj. R-squared:                  0.229
Method:                 Least Squares   F-statistic:                     11.34
Date:                Wed, 17 Jun 2026   Prob (F-statistic):           2.21e-12
Time:                        11:22:53   Log-Likelihood:                -389.58
No. Observations:                 244   AIC:                             795.2
Df Residuals:                     236   BIC:                             823.1
Df Model:                           7
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept             1.2267      0.294      4.179      0.000       0.648       1.805
C(sex)[T.Female]     -0.1006      0.167     -0.602      0.548      -0.430       0.229
C(smoker)[T.No]      -0.2092      0.170     -1.229      0.220      -0.544       0.126
C(day)[T.Fri]        -0.2018      0.464     -0.435      0.664      -1.117       0.713
C(day)[T.Sat]        -0.3660      0.556     -0.658      0.511      -1.461       0.729
C(day)[T.Sun]        -0.2945      0.557     -0.529      0.597      -1.392       0.803
C(time)[T.Dinner]     0.4858      0.523      0.929      0.354      -0.545       1.516
size                  0.7100      0.084      8.409      0.000       0.544       0.876
==============================================================================
Omnibus:                       77.259   Durbin-Watson:                   1.867
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              255.388
Skew:                           1.322   Prob(JB):                     3.49e-56
Kurtosis:                       7.258   Cond. No.                         39.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""